### ISSUE TITLE
Installation failure with Pentaho 7

### ISSUE THREAD

**Issue by shivasakthi18** [it4biz/SaikuChartPlus#40]
2017/03/20 13:13:49 - Download Plugin - Connecting to URL: http://downloads.sourceforge.net/project/saikuchartplus/SaikuChartPlus3/saiku-chart-plus-vSaiku3-plugin-pentaho.zip
2017/03/20 13:13:49 - Download Plugin - Start reading reply from webserver.
2017/03/20 13:13:49 - Download Plugin - Resource type: text/html; charset=UTF-8, last modified on: Thu Jan 01 00:00:00 UTC 1970.
2017/03/20 13:13:49 - Download Plugin - Finished writing 425 bytes to result file [/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/downloads/saiku-chart-plus-2016.05.19_1490015629096.zip]
2017/03/20 13:13:49 - download_and_install_plugin - Starting entry [Unzip]
2017/03/20 13:13:49 - download_and_install_plugin - exec(2, 0, Unzip.0)
2017/03/20 13:13:49 - Unzip - Starting job entry
2017/03/20 13:13:49 - Unzip - Starting ...
2017/03/20 13:13:49 - Unzip - Processing row source File/folder source : [zip:${downloadDestination}] ... destination file/folder : [${stagingDestination}]... wildcard : [null]
2017/03/20 13:13:49 - Unzip - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : Can not copy file/folder [zip:/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/downloads/saiku-chart-plus-2016.05.19_1490015629096.zip] to [/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/staging/]. Exception : [
2017/03/20 13:13:49 - Unzip -
2017/03/20 13:13:49 - Unzip - Unable to get VFS File object for filename 'zip:/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/downloads/saiku-chart-plus-2016.05.19_1490015629096.zip' : Could not open Zip file "/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/downloads/saiku-chart-plus-2016.05.19_1490015629096.zip".
2017/03/20 13:13:49 - Unzip -
2017/03/20 13:13:49 - Unzip - ]
2017/03/20 13:13:49 - Unzip - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : org.pentaho.di.core.exception.KettleFileException:
2017/03/20 13:13:49 - Unzip -
2017/03/20 13:13:49 - Unzip - Unable to get VFS File object for filename 'zip:/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/downloads/saiku-chart-plus-2016.05.19_1490015629096.zip' : Could not open Zip file "/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/downloads/saiku-chart-plus-2016.05.19_1490015629096.zip".
2017/03/20 13:13:49 - Unzip -
2017/03/20 13:13:49 - Unzip -
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.core.vfs.KettleVFS.getFileObject(KettleVFS.java:159)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.core.vfs.KettleVFS.getFileObject(KettleVFS.java:106)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.entries.copyfiles.JobEntryCopyFiles.ProcessFileFolder(JobEntryCopyFiles.java:427)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.entries.copyfiles.JobEntryCopyFiles.execute(JobEntryCopyFiles.java:382)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.Job.execute(Job.java:724)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.Job.execute(Job.java:865)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.Job.execute(Job.java:865)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.Job.execute(Job.java:546)
2017/03/20 13:13:49 - Unzip -   at org.pentaho.di.job.Job.run(Job.java:436)
2017/03/20 13:13:49 - download_and_install_plugin - Starting entry [Unzipped Plugin Exists]
2017/03/20 13:13:49 - download_and_install_plugin - exec(3, 0, Unzipped Plugin Exists.0)
2017/03/20 13:13:49 - Unzipped Plugin Exists - Starting job entry
2017/03/20 13:13:49 - Unzipped Plugin Exists - File [/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/staging/saiku-chart-plus] does not exist!
2017/03/20 13:13:49 - download_and_install_plugin - Starting entry [Cleanup Staging]
2017/03/20 13:13:49 - download_and_install_plugin - exec(4, 0, Cleanup Staging.0)
2017/03/20 13:13:49 - Cleanup Staging - Starting job entry
2017/03/20 13:13:49 - Cleanup Staging - Processing folder [/home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/staging/]
2017/03/20 13:13:49 - Cleanup Staging - Folder /home/olapadm/pentaho7/pentaho-server/pentaho-solutions/system/plugin-cache/staging/ was deleted. Total deleted files = 1
2017/03/20 13:13:49 - Cleanup Staging - =======================================
2017/03/20 13:13:49 - Cleanup Staging - Number of errors : 0
2017/03/20 13:13:49 - Cleanup Staging - Number of deleted folders : 1
2017/03/20 13:13:49 - Cleanup Staging - =======================================
2017/03/20 13:13:49 - download_and_install_plugin - Starting entry [Abort job]
2017/03/20 13:13:49 - download_and_install_plugin - exec(5, 0, Abort job.0)
2017/03/20 13:13:49 - Abort job - Starting job entry
2017/03/20 13:13:49 - Abort job - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : Plugin did not contain ID
2017/03/20 13:13:49 - download_and_install_plugin - Finished job entry [Abort job] (result=[false])
2017/03/20 13:13:49 - download_and_install_plugin - Finished job entry [Cleanup Staging] (result=[false])
2017/03/20 13:13:49 - download_and_install_plugin - Finished job entry [Unzipped Plugin Exists] (result=[false])
2017/03/20 13:13:49 - download_and_install_plugin - Finished job entry [Unzip] (result=[false])
2017/03/20 13:13:49 - download_and_install_plugin - Finished job entry [Download Plugin] (result=[false])
2017/03/20 13:13:49 - download_and_install_plugin - Job execution finished

**Comment by jwazne** [comment]
Hi,

Same error when trying to install Saiku Plugin 3.90 STABLEP7 with Pentaho 8.1
